import { Contact, Company, Deal, Task } from '@/types';

export const seedContacts: Contact[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Inc',
    position: 'CTO',
    status: 'active',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@innovate.io',
    phone: '+1 (555) 234-5678',
    company: 'Innovate Solutions',
    position: 'CEO',
    status: 'active',
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-02-10').toISOString(),
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'mjohnson@dataflow.com',
    phone: '+1 (555) 345-6789',
    company: 'DataFlow Systems',
    position: 'VP of Sales',
    status: 'active',
    createdAt: new Date('2024-03-05').toISOString(),
    updatedAt: new Date('2024-03-05').toISOString(),
  },
];

export const seedCompanies: Company[] = [
  {
    id: '1',
    name: 'TechCorp Inc',
    industry: 'Technology',
    website: 'https://techcorp.com',
    phone: '+1 (555) 100-0001',
    address: '123 Tech Street, San Francisco, CA 94105',
    employees: 500,
    revenue: 50000000,
    status: 'active',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    name: 'Innovate Solutions',
    industry: 'Software',
    website: 'https://innovate.io',
    phone: '+1 (555) 200-0002',
    address: '456 Innovation Ave, Austin, TX 78701',
    employees: 250,
    revenue: 25000000,
    status: 'active',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '3',
    name: 'DataFlow Systems',
    industry: 'Data Analytics',
    website: 'https://dataflow.com',
    phone: '+1 (555) 300-0003',
    address: '789 Data Drive, Seattle, WA 98101',
    employees: 150,
    revenue: 15000000,
    status: 'active',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
];

export const seedDeals: Deal[] = [
  {
    id: '1',
    title: 'Enterprise Software License',
    value: 150000,
    stage: 'proposal',
    probability: 60,
    contactId: '1',
    companyId: '1',
    expectedCloseDate: new Date('2024-12-31').toISOString(),
    createdAt: new Date('2024-10-01').toISOString(),
    updatedAt: new Date('2024-10-15').toISOString(),
  },
  {
    id: '2',
    title: 'Cloud Migration Project',
    value: 250000,
    stage: 'negotiation',
    probability: 80,
    contactId: '2',
    companyId: '2',
    expectedCloseDate: new Date('2024-11-30').toISOString(),
    createdAt: new Date('2024-09-15').toISOString(),
    updatedAt: new Date('2024-10-20').toISOString(),
  },
  {
    id: '3',
    title: 'Data Analytics Platform',
    value: 100000,
    stage: 'qualified',
    probability: 40,
    contactId: '3',
    companyId: '3',
    expectedCloseDate: new Date('2025-01-31').toISOString(),
    createdAt: new Date('2024-10-10').toISOString(),
    updatedAt: new Date('2024-10-10').toISOString(),
  },
];

export const seedTasks: Task[] = [
  {
    id: '1',
    title: 'Follow up with John Doe',
    description: 'Discuss enterprise license requirements',
    status: 'todo',
    priority: 'high',
    dueDate: new Date('2024-11-10').toISOString(),
    assignedTo: 'Sales Team',
    relatedTo: { type: 'contact', id: '1' },
    createdAt: new Date('2024-11-01').toISOString(),
    updatedAt: new Date('2024-11-01').toISOString(),
  },
  {
    id: '2',
    title: 'Prepare proposal for Innovate Solutions',
    description: 'Create detailed cloud migration proposal',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date('2024-11-08').toISOString(),
    assignedTo: 'Technical Team',
    relatedTo: { type: 'deal', id: '2' },
    createdAt: new Date('2024-10-25').toISOString(),
    updatedAt: new Date('2024-11-02').toISOString(),
  },
  {
    id: '3',
    title: 'Schedule demo with DataFlow',
    description: 'Set up product demonstration',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2024-11-15').toISOString(),
    assignedTo: 'Sales Team',
    relatedTo: { type: 'company', id: '3' },
    createdAt: new Date('2024-11-03').toISOString(),
    updatedAt: new Date('2024-11-03').toISOString(),
  },
];
